# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 9, 30, 21, 25, 40, 728921, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
